In [ ]:
Section A: Data Structures & Control Structures

In [ ]:
1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [2]:
#creating a list and performing different list operations
list=[1,2,3,4,5]
list.append(6) #append a element in list
list

[1, 2, 3, 4, 5, 6]

In [4]:
#extend
list=[1,2,3,4,5]
list.extend([6,7,8]) #it will used for extending a list by adding multiple items in list
list

[1, 2, 3, 4, 5, 6, 7, 8]

In [5]:
#insert
list=[1,2,3,4,5]
list.insert(2,18) #it will insert the element in a index position
list

[1, 2, 18, 3, 4, 5]

In [10]:
#remove
list=[1,2,3,4,5]
list.remove(3) #it will remove the element in the list
list

[1, 2, 4, 5]

In [16]:
#pop
list=[1,2,3,4,5]
list.pop()  #it removes element from last if we give index position then it will remove from that index elemnet
list

[1, 2, 3, 4]

In [17]:
#clear
list=[1,2,3,4,5]
list.clear() #it will clear all the list
list

[]

In [23]:
#index
list=[1,2,3,4,5]
list.index(2) #it will returns the index value of the element

1

In [27]:
#count
list=[1,2,2,3,4]
list.count(2) #it will count the frequency of a element


2

In [29]:
#sort
list=[5,4,3,2,1]
list.sort() #it will sort the list in ascending order
list

[1, 2, 3, 4, 5]

In [31]:
#reversr
list=[1,2,3,4,5]
list.reverse() # it will reverse the list
list

[5, 4, 3, 2, 1]

In [ ]:
2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [34]:
#create a tuple
tuple=("rohith","satya","harshith")
tuple[1]="bhanu"

TypeError: 'tuple' object does not support item assignment

In [ ]:
# Tuple is a immutable which means we cannot change once it created, and we cannot modify any changes like adding,removing the elements

In [ ]:
3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [35]:
#Creating a duplicate set
set={1,2,2,2,3,4,5,5,6}
set

{1, 2, 3, 4, 5, 6}

In [ ]:
#set removed the duplicate elements in th output
#set stores only unique elements in it.

In [30]:
4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary

In [40]:
#Creating a dictionary with keys
dict={
    'name':"Rohith",
    "age":20,
    "city":"Hyderabad"
}
dict["age"]=25   #age got updated
dict["emial"]="rohith@gmail.com" #new key email has added
dict


{'name': 'Rohith', 'age': 25, 'city': 'Hyderabad', 'emial': 'rohith@gmail.com'}

In [ ]:
5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [41]:
#code for eligible to vote
age=int(input("enter your age :"))
if(age>=18):
  print("you are eligible to vote")
else:
  print("you are not eligible to vote")

enter your age :25
you are eligible to vote


In [ ]:
6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [45]:
#code for grade
marks=int(input("enter your marks :"))
if(marks>=90):
  print("Grade A")
elif(marks>=75 and marks<=89):
  print("Grade B")
elif(marks>=50 and marks<=74):
  print("Grade C")
else:
  print("Fail")

enter your marks :95
Grade A


In [ ]:
7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.52

In [53]:
#checking a number code
number = int(input("enter your number :"))
if(number>0):
  if(number%2==0):
    print(f"{number} is positive and even")
  else:
    print(f"{number} is positive and odd")
else:
  if(number==0):
    print(f"{number} is zero")
  else:
    print(f"{number} is negative")


enter your number :8
8 is positive and even


In [47]:
Section B: Numpy

In [ ]:
8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [62]:
import numpy as np

scalar=np.array(5)
print("Scalar")
print("Shape :",scalar.shape)
print("Dimensions :",scalar.ndim)

Scalar
Shape : ()
Dimensions : 0


In [69]:
one_dime=np.array([1,2,3,4,5])
print("One Dimension array")
print("Shape :",one_dime.shape)
print("Dimensions :",one_dime.ndim)
print(one_dime)

One Dimension array
Shape : (5,)
Dimensions : 1
[1 2 3 4 5]


In [71]:
two_dim=np.arange(10,70,10).reshape(2,3)
print("Two Dimensional Array")
print("Shape :",two_dim.shape)
print("Dimension :",two_dim.ndim)
print(two_dim)

Two Dimensional Array
Shape : (2, 3)
Dimension : 2
[[10 20 30]
 [40 50 60]]


In [ ]:
9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [74]:
import numpy as np
generating_numbers = np.random.randint(0,100,(4,4))
print(generating_numbers)


[[64 58 21 92]
 [24  1 59 92]
 [41 23 87 16]
 [36  6 42 29]]


In [ ]:
10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [127]:
#creating a 2d array
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
pd.DataFrame(arr)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [80]:
pd.DataFrame(arr,columns=['A','B','C'])

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
Section C: Exploring Pandas

In [ ]:
11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [130]:
import pandas as pd
import numpy as np
data = {
    "Name": ["Ravi", "Anita", "Kiran", "Ravi", "Vijay",
             "Meena", "Arjun", "Priya", "Rahul", "Neha"],
    "Age": [25, 28, 22, 30, 35,
            27, 24, 29, 26, 23],
    "City": ["Delhi", "Mumbai", "Bangalore", "Hyderabad", "Chennai",
             "Pune", "Kolkata", "Jaipur", "Ahmedabad", "Lucknow"],
    "Salary": [50000, 60000, np.nan, 70000, 80000,
               55000, 48000, np.nan, 52000, 47000]
}
df = pd.DataFrame(data)
df


Name  Age       City   Salary
0   Ravi   25      Delhi  50000.0
1  Anita   28     Mumbai  60000.0
2  Kiran   22  Bangalore      NaN
3   Ravi   30  Hyderabad  70000.0
4  Vijay   35    Chennai  80000.0
5  Meena   27       Pune  55000.0
6  Arjun   24    Kolkata  48000.0
7  Priya   29     Jaipur      NaN
8  Rahul   26  Ahmedabad  52000.0
9   Neha   23    Lucknow  47000.0

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [123]:
df.describe()

Age        Salary
count  10.000000      8.000000
mean   26.900000  57750.000000
std     3.842742  11719.946368
min    22.000000  47000.000000
25%    24.250000  49500.000000
50%    26.500000  53500.000000
75%    28.750000  62500.000000
max    35.000000  80000.000000

In [132]:
df[['Name','City']]

Name       City
0   Ravi      Delhi
1  Anita     Mumbai
2  Kiran  Bangalore
3   Ravi  Hyderabad
4  Vijay    Chennai
5  Meena       Pune
6  Arjun    Kolkata
7  Priya     Jaipur
8  Rahul  Ahmedabad
9   Neha    Lucknow

In [133]:
df.drop('City',axis=1)

Name  Age   Salary
0   Ravi   25  50000.0
1  Anita   28  60000.0
2  Kiran   22      NaN
3   Ravi   30  70000.0
4  Vijay   35  80000.0
5  Meena   27  55000.0
6  Arjun   24  48000.0
7  Priya   29      NaN
8  Rahul   26  52000.0
9   Neha   23  47000.0

In [134]:
mean_salary=df['Salary'].mean()
df['Salary'].fillna(mean_salary,inplace=True)
df

Name  Age       City   Salary
0   Ravi   25      Delhi  50000.0
1  Anita   28     Mumbai  60000.0
2  Kiran   22  Bangalore  57750.0
3   Ravi   30  Hyderabad  70000.0
4  Vijay   35    Chennai  80000.0
5  Meena   27       Pune  55000.0
6  Arjun   24    Kolkata  48000.0
7  Priya   29     Jaipur  57750.0
8  Rahul   26  Ahmedabad  52000.0
9   Neha   23    Lucknow  47000.0

In [141]:
dup=df.drop_duplicates('Name')
dup

Name  Age       City   Salary
0   Ravi   25      Delhi  50000.0
1  Anita   28     Mumbai  60000.0
2  Kiran   22  Bangalore  57750.0
4  Vijay   35    Chennai  80000.0
5  Meena   27       Pune  55000.0
6  Arjun   24    Kolkata  48000.0
7  Priya   29     Jaipur  57750.0
8  Rahul   26  Ahmedabad  52000.0
9   Neha   23    Lucknow  47000.0